name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: VEX Build
      uses: schineaj23/vex-build@v1.0
      with:
        path: MyProject1/
