name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: MyProject1/make
      run: MyProject1/make
    - name: MyProject1/make check
      run: MyProject1/make check
    - name: MyProject1/make distcheck
      run: MyProject1/make distcheck
